<?php

/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */

 echo $block->sayHello();
 ?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

.icon-star:before { content: "★ "; }


</style>

<span><span class="icon-star" aria-hidden="true"></span>Test action</span>



</body>
</html>